// export * from './Button'
import Avatar from './Avatar'
import H3 from './H3'
import Button from './Button'
import PokemonType from './Type'
import InputForm from './InputForm'
import Closed from './Closed'
import NotFound from './NotFound'
import ArrowButton from './ArrowButton'
export {Avatar, H3, Button, PokemonType, InputForm, Closed, NotFound, ArrowButton}